services:
  - type: web
    name: web-development
    env: python
    pythonVersion: 3.12.3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
